name: CI/CD -> Render

on:
  push:
  workflow_dispatch:

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Render deploy (deploy hook)
        if: success()
        run: |
          # adiciona ?ref=<sha> para forçar deploy do commit atual (opcional)
          curl -X POST -sS --fail "${{ secrets.RENDER_DEPLOY_HOOK_URL }}?ref=${{ github.sha }}" >/dev/null
